# Generated by Django 4.2.6 on 2024-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyCuaHangSet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='ngay_lap',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
