# Generated by Django 5.1 on 2024-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyCuaHangSet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='phuong_thuc_thanh_toan',
            field=models.CharField(choices=[('transfer', 'Chuyển khoản'), ('cash', 'Tiền mặt')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='trang_thai',
            field=models.CharField(choices=[('prep', 'Đang chuẩn bị'), ('deliv', 'Đang giao hàng'), ('del', 'Giao thành công')], default='prep', max_length=10),
        ),
    ]
