# Generated by Django 5.1 on 2024-09-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyCuaHangSet', '0002_hoadon_phuong_thuc_thanh_toan_hoadon_trang_thai'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaChiGiaoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ho_ten', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.TextField()),
                ('mac_dinh', models.BooleanField(default=False)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_chi_giao_hang', to='QuanLyCuaHangSet.khachhang')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
