# Generated by Django 5.1 on 2024-09-01 16:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyCuaHangSet', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_anh',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
